namespace DiskTempMonitor.Services;

/// <summary>Tabella dei nomi degli attributi S.M.A.R.T. ATA più comuni.</summary>
internal static class SmartNames
{
    private static readonly Dictionary<byte, string> Map = new()
    {
        [0x01] = "Raw Read Error Rate",
        [0x02] = "Throughput Performance",
        [0x03] = "Spin-Up Time",
        [0x04] = "Start/Stop Count",
        [0x05] = "Reallocated Sectors Count",
        [0x06] = "Read Channel Margin",
        [0x07] = "Seek Error Rate",
        [0x08] = "Seek Time Performance",
        [0x09] = "Power-On Hours",
        [0x0A] = "Spin Retry Count",
        [0x0B] = "Recalibration Retries",
        [0x0C] = "Power Cycle Count",
        [0x0D] = "Soft Read Error Rate",
        [0x16] = "Current Helium Level",
        [0xAA] = "Available Reserved Space",
        [0xAB] = "Program Fail Count",
        [0xAC] = "Erase Fail Count",
        [0xAD] = "Wear Leveling Count",
        [0xAE] = "Unexpected Power Loss Count",
        [0xAF] = "Power Loss Protection Failure",
        [0xB0] = "Erase Fail Count (chip)",
        [0xB1] = "Wear Range Delta",
        [0xB2] = "Used Reserved Block Count",
        [0xB3] = "Used Reserved Block Count (total)",
        [0xB4] = "Unused Reserved Block Count",
        [0xB5] = "Program Fail Count (total)",
        [0xB6] = "Erase Fail Count",
        [0xB7] = "SATA Downshift Error Count",
        [0xB8] = "End-to-End Error",
        [0xB9] = "Head Stability",
        [0xBA] = "Induced Op-Vibration Detection",
        [0xBB] = "Reported Uncorrectable Errors",
        [0xBC] = "Command Timeout",
        [0xBD] = "High Fly Writes",
        [0xBE] = "Airflow Temperature",
        [0xBF] = "G-Sense Error Rate",
        [0xC0] = "Power-Off Retract Count",
        [0xC1] = "Load/Unload Cycle Count",
        [0xC2] = "Temperature",
        [0xC3] = "Hardware ECC Recovered",
        [0xC4] = "Reallocation Event Count",
        [0xC5] = "Current Pending Sector Count",
        [0xC6] = "Uncorrectable Sector Count",
        [0xC7] = "UltraDMA CRC Error Count",
        [0xC8] = "Write Error Rate",
        [0xC9] = "Soft Read Error Rate",
        [0xCA] = "Data Address Mark Errors",
        [0xCB] = "Run Out Cancel",
        [0xCC] = "Soft ECC Correction",
        [0xCD] = "Thermal Asperity Rate",
        [0xCE] = "Flying Height",
        [0xCF] = "Spin High Current",
        [0xD0] = "Spin Buzz",
        [0xD1] = "Offline Seek Performance",
        [0xD2] = "Vibration During Write",
        [0xD3] = "Vibration During Write",
        [0xD4] = "Shock During Write",
        [0xDC] = "Disk Shift",
        [0xDD] = "G-Sense Error Rate",
        [0xDE] = "Loaded Hours",
        [0xDF] = "Load/Unload Retry Count",
        [0xE0] = "Load Friction",
        [0xE1] = "Load/Unload Cycle Count",
        [0xE2] = "Load-In Time",
        [0xE3] = "Torque Amplification Count",
        [0xE4] = "Power-Off Retract Cycle",
        [0xE6] = "GMR Head Amplitude / Life Curve",
        [0xE7] = "Temperature / SSD Life Left",
        [0xE8] = "Endurance Remaining",
        [0xE9] = "Media Wearout Indicator",
        [0xEA] = "Total LBAs Written (GiB)",
        [0xEB] = "Good/System Block Count",
        [0xF0] = "Head Flying Hours",
        [0xF1] = "Total LBAs Written",
        [0xF2] = "Total LBAs Read",
        [0xF3] = "Total LBAs Written Expanded",
        [0xF4] = "Total LBAs Read Expanded",
        [0xF5] = "Remaining Rated Write Endurance",
        [0xF6] = "Cumulative Host Sectors Written",
        [0xF7] = "Host Program Page Count",
        [0xF8] = "Background Program Page Count",
        [0xF9] = "NAND Writes (1 GiB)",
        [0xFA] = "Read Error Retry Rate",
        [0xFB] = "Minimum Spares Remaining",
        [0xFC] = "Newly Added Bad Flash Block",
        [0xFE] = "Free Fall Protection",
    };

    public static string Get(byte id) => Map.TryGetValue(id, out var n) ? n : $"Attributo sconosciuto {id:X2}h";

    /// <summary>Attributi il cui valore grezzo diverso da zero è considerato critico.</summary>
    public static bool IsCritical(byte id) =>
        id is 0x05 or 0xC4 or 0xC5 or 0xC6 or 0xBB or 0xB8;

    /// <summary>Attributi che contengono una temperatura in gradi Celsius.</summary>
    public static bool IsTemperature(byte id) => id is 0xC2 or 0xBE or 0xE7;
}
